name: epub_search
description: A package for searching across multiple EPUB books
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  epub_parser: ^3.0.1
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  freezed: ^2.0.0
